version: "3"
services:
  app:
    depends_on:
      - mongo
    restart: always
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata:
