name: Test
on:
  pull_request:
  push:
    branches: master

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn tsc

      - name: Test with Coverage
        run: yarn test:cov

      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
